name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        #        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
        #        run: docker login -u AWS -p $(aws ecr get-login-password --region ap-southeast-2) 975050237888.dkr.ecr.ap-southeast-2.amazonaws.com
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 975050237888.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build Docker image
        run: docker build -t hankhan/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true hankhan/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x '.idea' -x '.dockerignore' -x 'Dockerfile.dev' -x 'docker-compose.*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ vars.APPLICATION_NAME }}
          environment_name: ${{ vars.ENVIRONMENT_NAME }}
          existing_bucket_name: ${{ vars.EXISTING_BUCKET_NAME }}
          region: ${{ vars.REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
